name: 'Node.js Production Test Action'
description: 'Run a test script against a package as a consumer would'
inputs:
  script:
    description: 'npm script name (as in the `scripts` prop of `package.json``) to run'
    required: true
  scriptArgs:
    description: 'Space-delimited list of extra arguments (including any leading dashes) to pass to the script.'
    required: false
  workspace:
    description: 'Space-delimited list of one or more npm workspace names, paths, or a path to a workspace dir. Corresponds to the `--workspace` argument of `npm pack`. If present, will cause `npm run-script` to run for each resulting installation.'
    required: false
  workspaces:
    description: 'Pack all workspaces. Corresponds to the `--workspaces` flag of `npm pack`. If true, will cause `npm run-script` to run for each resulting installation. _Boolean._'
    required: false
    default: 'false'
  includeWorkspaceRoot:
    description: 'If `workspaces` is true, also pack the workspace root. Corresponds to the `--include-workspace-root` flag of `npm pack`. _Boolean._'
    required: false
    default: 'false'
  extraNpmInstallArgs:
    description: 'Space-delimited list of extra arguments (including any leading dashes; e.g., `--ignore-scripts`) to use with `npm install /path/to/tarball.tgz`.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
