name: Node CI

on: [pull_request, push]

jobs:
  build:
    name: Production Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - name: Production Test Action
        uses: ./dist/index.js
        with:
          script: production-test
