name: Node CI

on: [pull_request, push]

jobs:
  build:
    name: Production Test
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        uses: bahmutov/npm-install@v1
      - name: Production Test Action
        uses: boneskull/nodejs-production-test-action@v1
        with:
          script: production-test
