name: Node CI

on: [pull_request, push]

jobs:
  build:
    name: Production Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Production Test Action
        uses: boneskull/nodejs-production-test-action@v1
        with:
          script: production-test
